#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
        set -x
fi

set -eu
set -o pipefail

ssh-keygen -t rsa -N -f /etc/ssh/ssh_host_rsa_key
ssh-keygen -t dsa -N -f /etc/ssh/ssh_host_dsa_key
ssh-keygen -t ecdsa -N -f /etc/ssh/ssh_host_ecdsa_key
