#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
        set -x
fi

set -eu
set -o pipefail

apt-get -y remove ufw acpid whoopsie apparmor apport apport-symptoms rpcbind ubuntu-standard update-manager-core update-notifier-common usbutils uuid-runtime whoopsie wireless-tools

# make sure everything from whoopsie and acpid is gone
dpkg --purge whoopsie
dpkg --purge acpid

cat > /etc/fstab << EOF
# This file is not used on vserver guests
EOF
