#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
        set -x
fi

set -eu
set -o pipefail

apt-get -y remove ufw acpid whoopsie

cat > /etc/fstab << EOF
# This file is not used on vserver guests
EOF
