#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -f "/etc/collectd/collectd.conf" ]; then
    cp /etc/collectd/collectd.conf /etc/collectd/collectd.conf.orig
fi

cat <<EOF > /etc/collectd/collectd.conf
FQDNLookup True
Interval 10
Timeout 2
ReadThreads 5
LoadPlugin cpu
LoadPlugin interface
LoadPLugin network
<Plugin network>
        Server "fdca:3ba5:a17a:acda::1"
</Plugin>

EOF
