#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

mkdir -p /root/.ssh
chmod 0700 /root/.ssh

if [ ! -f "/tmp/in_target.d/akanda-authorized-keys" ]; then
    echo "The ssh public key for the root user is not available, exiting"
    exit 1
fi

cat /tmp/in_target.d/akanda-authorized-keys >> /root/.ssh/authorized_keys
chmod 0600 /root/.ssh/authorized_keys

if [ ! -f "/tmp/in_target.d/akanda-root-pass" ]; then
    echo "The password for the root user is not available, exiting"
    exit 1
fi

cat /tmp/in_target.d/akanda-root-pass | chpasswd -e
