#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -f "/etc/sysctl.conf" ]; then
    cp /etc/sysctl.conf /etc/sysctl.conf.orig
fi

cat >> /etc/sysctl.conf <<EOF
net.ipv6.conf.default.accept_dad=0
net.ipv6.conf.eth0.accept_dad=0
net.ipv6.conf.eth1.accept_dad=1
net.ipv6.conf.eth2.accept_dad=0
net.ipv4.conf.all.arp_announce=2
net.ipv4.conf.default.arp_notify=1
net.ipv4.conf.all.arp_notify=1
net.ipv4.neigh.default.gc_thresh1=4096
net.ipv4.neigh.default.gc_thresh2=8192
net.ipv4.neigh.default.gc_thresh3=8192
net.ipv6.neigh.default.gc_thresh1=4096
net.ipv6.neigh.default.gc_thresh2=8192
net.ipv6.neigh.default.gc_thresh3=8192
EOF
