#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

DIB_DISTRIBUTION_MIRROR=${DIB_DISTRIBUTION_MIRROR:-http://archive.ubuntu.com/ubuntu}

# We should manage this in a betterer way
cat << EOF >/etc/apt/sources.list
deb $DIB_DISTRIBUTION_MIRROR $DIB_RELEASE main restricted universe multiverse
deb $DIB_DISTRIBUTION_MIRROR $DIB_RELEASE-updates main restricted universe multiverse
deb $DIB_DISTRIBUTION_MIRROR $DIB_RELEASE-backports main restricted universe multiverse
deb $DIB_DISTRIBUTION_MIRROR $DIB_RELEASE-security main restricted universe multiverse
EOF

apt-get update
apt-get clean
