#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
        set -x
fi

set -eu
set -o pipefail

curl -L -o /tmp/chef.deb $CHEF_URL && dpkg -i /tmp/chef.deb

cat > /tmp/chef-dna.json << EOF
{
  "vps_type": "${VPS_TYPE}",
  "run_list": [
        "recipe[$VPS_CHEF_RECIPE]"
   ]
}
EOF

chef-client -z -c /tmp/chef-solo.rb -j /tmp/chef-dna.json
