#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

PATCHES_FOLDER="$(dirname $0)/../patches"
PY_VERSION=$(basename $(readlink -f `which python3`))
patch -p1 /usr/lib/$PY_VERSION/site-packages/cloudinit/distros/rhel_util.py $PATCHES_FOLDER/cloud-init-fix-resolvconf-encode.patch
patch -p1 /usr/lib/$PY_VERSION/site-packages/cloudinit/sources/helpers/openstack.py $PATCHES_FOLDER/cloud-init-fix-network-file-decode.patch
